### ISSUE TITLE
logging error

### ISSUE THREAD

**Issue by briziorusso** [RobuSTAI/RobuSTAI#35]
https://github.com/RobuSTAI/RobuSTAI/commit/24d2663ee480ef5046a7610babd429f926fccd0a#commitcomment-47843232

**Comment by briziorusso** [comment]
This also prevents main.py to run with test. The error appears to happen when `predictor.evaluate()` is called. The errors are the following:

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [419,0,0], thread: [96,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
...
Traceback (most recent call last):
  File "main.py", line 112, in <module>
    main()
  File "main.py", line 107, in main
    outputs = predictor.evaluate()
  File "/vol/bitbucket/fr920/envs/nlpoi/lib/python3.6/site-packages/transformers/trainer.py", line 1449, in evaluate
    metric_key_prefix=metric_key_prefix,
... 
  File "/vol/bitbucket/fr920/envs/nlpoi/lib/python3.6/site-packages/torch/nn/functional.py", line 1692, in linear
    output = input.matmul(weight.t())
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`


I tried to switch off cuda but it gets stuck, I guess it's too big?

Also found something around the inputs not being well set:
_I’ve been having this issue with RoBERTa. The problem was the max_position_embeddings parameter must be larger than the max_seq_length, otherwise the position embedding can generate indices > max_position_embeddings_ (from https://discuss.pytorch.org/t/solved-assertion-srcindex-srcselectdimsize-failed-on-gpu-for-torch-cat/1804/21)

and noticed that our eval_dataset still had the stuff that we're supposed to get rid of with the training_ and prediction_step() overrides i.e.

- guid
- meta

is this normal @alexgaskell10 ??

I'm afraid but at this point I'm a bit stuck, can you help?
